Fork cleanup, comments, removed redundant replay.

diff --git a/bnc b/bnc
--- a/bnc
+++ b/bnc
@@ -2,43 +2,36 @@
 # An IRC bouncer (BNC) in Bash.
 
 relay() {
-    declare in="$1" out="$2" log="$3" host="$4" port="${5:-6667}"
+    declare in="$1" out="$2" logfile="$3" host="$4" port="${5:-6667}"
     echo "Connecting to IRC server on ${host}:${port}."
-    nc "$host" "$port" < "$in"  | logger "[relay] " "$log" > "$out"
+    nc "$host" "$port" < "$in"  | logger "[relay] " "$logfile" > "$out"
     echo "Lost connection to IRC server."
 }
 
 client() {
-    declare in="$1" out="$2" log="$3" host="${4:-localhost}" port="${5:-16667}"
+    declare in="$1" out="$2" logfile="$3" host="${4:-localhost}" port="${5:-16667}"
     echo "Listening for IRC clients on ${host}:${port}."
     while [ 1 ]; do
         nc -l "$host" "$port" < "$in"
 
         # Replay log.
-        # TODO: Replay only the parts we actually need.
-        cat "$log" > "$in" &
+        # TODO: Replay only the parts we actually need?
+        cat "$logfile" > "$in" &
     done | client_middleware | logger "[client]" > "$out"
 }
 
 client_middleware() {
+    # Consume messages we don't want to relay.
     local connected=0
     while read line; do
+        # Parse commands, look like this: "COMMAND args..."
         local command="$(echo $line | cut -d ' ' -f1)"
         case "$command" in
             "QUIT")
                 # Discard QUIT messages, because we're not quitters.
                 continue
                 ;;
-            "NICK")
-                if [[ $connected -ge 2 ]]; then
-                    # Skip logging in again.
-                    echo "Skipping welcome: $line" > /dev/stderr
-                    continue
-                fi
-                ((connected=connected+1))
-                echo "$line"
-                ;;
-            "USER")
+            "NICK" | "USER" | "PASS")
                 if [[ $connected -ge 2 ]]; then
                     # Skip logging in again.
                     echo "Skipping welcome: $line" > /dev/stderr
@@ -54,12 +47,12 @@ client_middleware() {
 }
 
 logger() {
-    declare prefix="$1" log="$2"
-    # Consume some messages, like QUIT
+    # Helper for debugging (output to stderr) and replay (logfile)
+    declare prefix="$1" logfile="$2"
     while read line; do
         echo "${prefix} ${line}" > /dev/stderr
-        if [[ "$log" ]]; then
-            echo "${line}" >> "$log"
+        if [[ "$logfile" ]]; then
+            echo "${line}" >> "$logfile"
         fi
         echo "${line}"
     done
@@ -84,12 +77,16 @@ main() {
 
     # Setup temporary workdir for our fifos.
     readonly workdir="$(mktemp -d -t $(basename $0))"
+
+    # Cleanup
     trap 'rm -rf "$workdir"' EXIT
+    trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
 
     mkfifo "$workdir/in" "$workdir/out"
     client "$workdir/in" "$workdir/out" "$workdir/irc.log" "localhost" "16667" &
-    # TODO: MITM between receive and relay.
     relay "$workdir/out" "$workdir/in" "$workdir/irc.log" "$1" "$2"
+    # TODO: Make sure client loop dies with the relay
+    # TODO: Defer opening relay until first client connected?
 }
 
 main $@
